conf_site/api/urls.py
from django.conf.urls import include, re_path
from rest_framework.routers import SimpleRouter

from . import views


# Create a router and register our viewsets with it.
router = SimpleRouter()
router.register(r'speaker', views.SpeakerViewSet)
router.register(r'presentation', views.PresentationViewSet)

urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^$', views.ConferenceDetail.as_view(), name='conference-detail'),
]

conf_site/proposals/urls.py
from django.conf.urls import include
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from conf_site.proposals.views import (
    ExportProposalSubmittersView,
    ExportProposalsView,
    ExportSubmissionsView,
)


urlpatterns = [
    path(
        "export/",
        staff_member_required(ExportProposalsView.as_view()),
        name="proposal_export",
    ),
    path(
        "submissions/export/",
        staff_member_required(ExportSubmissionsView.as_view()),
        name="submission_export",
    ),
    path(
        "submitters/export/",
        staff_member_required(ExportProposalSubmittersView.as_view()),
        name="proposal_submitter_export",
    ),
    path("", include("symposion.proposals.urls")),
]

conf_site/reviews/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from conf_site.reviews.views import (
    ProposalDetailView,
    ProposalFeedbackPostView,
    ProposalKindListView,
    ProposalReviewRequestedListView,
    ProposalListView,
    ProposalVotePostView,
    ReviewerListView,
)
from conf_site.reviews.views.export import ExportReviewersView
from conf_site.reviews.views.importing import (
    ReviewerCsvImportView,
    ReviewerProposalMatchingCsvImportView,
)
from conf_site.reviews.views.keywords import (
    ReviewKeywordDetailView,
    ReviewKeywordListView,
)
from conf_site.reviews.views.results import (
    ProposalChangeResultPostView,
    ProposalResultListView,
    ProposalMultieditPostView,
)

urlpatterns = [
    path(
        "assigned/",
        ProposalReviewRequestedListView.as_view(),
        name="review_assigned",
    ),
    path(
        "edit/", ProposalMultieditPostView.as_view(), name="review_multiedit"
    ),
    path(
        "keyword/", ReviewKeywordListView.as_view(), name="review_keyword_list"
    ),
    path(
        "keyword/<slug:keyword_slug>/",
        ReviewKeywordDetailView.as_view(),
        name="review_keyword_detail",
    ),
    path(
        "kind/<kind>/",
        ProposalKindListView.as_view(),
        name="review_proposal_kind_list",
    ),
    path(
        "proposal/<int:pk>/",
        ProposalDetailView.as_view(),
        name="review_proposal_detail",
    ),
    path(
        "proposal/<int:pk>/feedback/",
        ProposalFeedbackPostView.as_view(),
        name="review_proposal_feedback",
    ),
    path(
        "proposal/<int:pk>/result/<status>/",
        ProposalChangeResultPostView.as_view(),
        name="review_proposal_change_result",
    ),
    path(
        "proposal/<int:pk>/vote/",
        ProposalVotePostView.as_view(),
        name="review_proposal_vote",
    ),
    path(
        "result/<status>/",
        ProposalResultListView.as_view(),
        name="review_proposal_result_list",
    ),
    path(
        "reviewers/export/",
        staff_member_required(ExportReviewersView.as_view()),
        name="reviewer_export",
    ),
    path(
        "reviewers/import/",
        ReviewerCsvImportView.as_view(),
        name="reviewer_import",
    ),
    path(
        "reviewers/match/",
        ReviewerProposalMatchingCsvImportView.as_view(),
        name="reviewer_matching_import",
    ),
    path("reviewers/", ReviewerListView.as_view(), name="reviewer_list"),
    path("", ProposalListView.as_view(), name="review_proposal_list"),
]

conf_site/urls.py
from django.conf import settings
from django.conf.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path
from django.views.generic.base import TemplateView

try:
    import debug_toolbar
except ImportError:
    pass
import symposion.views

from conf_site.core.views import csrf_failure, TimeZoneChangeView
from conf_site.schedule.views import (
    ExportPresentationSpeakerView,
    PresentationDetailView,
    PresentationRedirectView,
)
from conf_site.speakers.views import (
    ExportAcceptedSpeakerEmailView,
    SpeakerDetailView,
    SpeakerListView,
    SpeakerRedirectView,
)


WIKI_SLUG = r"(([\w-]{2,})(/[\w-]{2,})*)"

if settings.DEBUG:
    urlpatterns = [
        re_path(r"^__debug__/", include(debug_toolbar.urls)),
    ]
else:
    urlpatterns = []
urlpatterns += [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("allauth.urls")),
    re_path(r"^api/", include("conf_site.api.urls")),
    re_path(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
    re_path(
        r"^speaker/export/$",
        staff_member_required(ExportAcceptedSpeakerEmailView.as_view()),
        name="speaker_email_export",
    ),
    re_path(
        r"^speaker/list/$", SpeakerListView.as_view(), name="speaker_list"
    ),
    path(
        "speaker/profile/<int:pk>/",
        SpeakerRedirectView.as_view(),
        name="speaker_profile_redirect",
    ),
    path(
        "speaker/profile/<int:pk>/<slug:slug>/",
        SpeakerDetailView.as_view(),
        name="speaker_profile",
    ),
    re_path(r"^speaker/", include("symposion.speakers.urls")),
    re_path(r"^proposals/", include("conf_site.proposals.urls")),
    re_path(r"^reviews/", include("conf_site.reviews.urls")),
    path(
        "schedule/presentation/<int:pk>/",
        PresentationRedirectView.as_view(),
        name="schedule_presentation_redirect",
    ),
    path(
        "schedule/presentation/<int:pk>/<slug:slug>/",
        PresentationDetailView.as_view(),
        name="schedule_presentation_detail",
    ),
    re_path(
        r"^schedule/presentation/export/$",
        staff_member_required(ExportPresentationSpeakerView.as_view()),
        name="presentation_speaker_export",
    ),
    re_path(r"^schedule/", include("symposion.schedule.urls")),
    re_path(
        r"^time-zone/$", TimeZoneChangeView.as_view(), name="time_zone_change"
    ),
    re_path(r"^403-csrf/", csrf_failure, name="403-csrf"),
    re_path(r"^413/", TemplateView.as_view(template_name="413.html")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conf_site/proposals/models.py
from django.conf import settings
from django.core.cache import cache
from django.db import models

from constance import config
from multiselectfield import MultiSelectField
from symposion.proposals.models import ProposalBase, ProposalSection
from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase

from conf_site.reviews.models import ProposalVote
from symposion.markdown_parser import parse


class ProposalKeyword(TagBase):
    official = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Keyword"
        verbose_name_plural = "Keywords"


class ProposalTrack(TagBase):
    class Meta:
        verbose_name = "Track"
        verbose_name_plural = "Tracks"


class EditorTaggedProposal(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProposalKeyword,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class TaggedProposal(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProposalKeyword,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class UserTaggedProposal(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProposalKeyword,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class TrackTaggedProposal(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProposalTrack,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class Proposal(ProposalBase):

    YES_NO_OTHER_YES = "Y"
    YES_NO_OTHER_NO = "N"
    # https://en.wikipedia.org/wiki/Bartleby,_the_Scrivener
    YES_NO_OTHER_BARTLEBY = "O"

    UNDER_REPRESENTED_ETHNICITY = "R"
    UNDER_REPRESENTED_AGE = "A"
    UNDER_REPRESENTED_GENDER = "G"
    UNDER_REPRESENTED_SEXUAL_ORIENTATION = "S"
    UNDER_REPRESENTED_DISABILITY = "D"
    UNDER_REPRESENTED_SOCIOECON = "C"
    UNDER_REPRESENTED_EDUCATION = "E"
    UNDER_REPRESENTED_OPT_OUT = "O"
    UNDER_REPRESENTED_OTHER = "X"

    KNOWLEDGE_LEVELS = [
        (YES_NO_OTHER_NO, "No previous knowledge expected"),
        (YES_NO_OTHER_YES, "Previous knowledge expected"),
    ]
    YES_NO_BOOL_ANSWERS = (
        (True, "Yes"),
        (False, "No"),
    )
    YES_NO_OTHER_ANSWERS = (
        ("", "----"),
        (YES_NO_OTHER_YES, "Yes"),
        (YES_NO_OTHER_NO, "No"),
        (YES_NO_OTHER_BARTLEBY, "Prefer not to say"),
    )
    YES_NO_SPONSOR_ANSWERS = (
        ("", "----"),
        (YES_NO_OTHER_YES, "Yes, I can make an introduction"),
        (YES_NO_OTHER_NO, "No"),
    )
    UNDER_REPRESENTED_DETAILED_ANSWERS = (
        (UNDER_REPRESENTED_GENDER, "Gender identity"),
        (UNDER_REPRESENTED_SEXUAL_ORIENTATION, "Sexual orientation"),
        (UNDER_REPRESENTED_ETHNICITY, "Race or ethnicity"),
        (UNDER_REPRESENTED_AGE, "Age"),
        (UNDER_REPRESENTED_EDUCATION, "Educational background"),
        (UNDER_REPRESENTED_SOCIOECON, "Socioeconomic status or background"),
        (UNDER_REPRESENTED_DISABILITY, "Disability status"),
        (UNDER_REPRESENTED_OPT_OUT, "I decline to answer"),
        (UNDER_REPRESENTED_OTHER, "Other (please specify)"),
    )

    AFFILIATION_COMPANY = "C"
    AFFILIATION_SCHOOL = "S"
    AFFILIATION_INDEPENDENT = "I"
    AFFILIATIONS = (
        (AFFILIATION_COMPANY, "Company"),
        (AFFILIATION_SCHOOL, "School"),
        (AFFILIATION_INDEPENDENT, "Independent"),
    )

    prior_knowledge = models.CharField(
        choices=KNOWLEDGE_LEVELS,
        max_length=1,
        verbose_name="Prior Knowledge Expected",
    )
    prior_knowledge_details = models.CharField(
        blank=True,
        max_length=200,
        verbose_name=(
            "To attend the presentation, "
            "it would be recommended that "
            "the participant have some knowledge in:"
        ),
    )

    outline = models.TextField(
        "Brief Bullet Point Outline",
        blank=True,
        help_text=(
            "Brief outline. Will be made public "
            "if your proposal is accepted. Edit using "
            "<a href='https://daringfireball.net/projects/markdown/basics' "
            "target='_blank'>Markdown</a>."
        ),
    )
    outline_html = models.TextField(blank=True, editable=False)

    recording_online = models.BooleanField(
        "Is there a recording of this talk/tutorial already online?",
        default=False,
    )
    recording_url = models.URLField(
        blank=True, max_length=2083, verbose_name="If yes, what is the link?"
    )

    slides_url = models.URLField(
        blank=True,
        default="",
        help_text=("Location of slides for this proposal "
                   "(e.g. SlideShare, Google Drive)."),
        max_length=2083,
        verbose_name="Slides")
    code_url = models.URLField(
        blank=True,
        default="",
        help_text="Location of this proposal's code repository (e.g. Github).",
        max_length=2083,
        verbose_name="Repository")

    country = models.CharField(
        max_length=200, verbose_name="What is your country of residence?"
    )

    first_time_at_pydata = models.CharField(
        "Are you a first-time speaker?",
        choices=YES_NO_OTHER_ANSWERS,
        blank=True,
        default="",
        max_length=1)
    travel_at_own_expense = models.BooleanField(
        choices=YES_NO_BOOL_ANSWERS,
        default=True,
        verbose_name=(
            "Are you able to travel to Eindhoven at your own expense?"
        ),
    )
    affiliation = models.CharField(
        max_length=200,
        verbose_name="Affilation (Company, School, Independent)",
    )

    mentorship = models.BooleanField(
        choices=YES_NO_BOOL_ANSWERS,
        default=False,
        verbose_name=(
            "Would you like to be considered "
            "for our speaker mentorship program?"
        ),
    )
    mentoring = models.BooleanField(
        choices=YES_NO_BOOL_ANSWERS,
        default=False,
        verbose_name="Would you be interested in mentoring other speakers?",
    )

    phone_number = models.CharField(
        "Phone number - to be used for last-minute schedule changes",
        blank=True,
        default="",
        max_length=100)
    recording_release = models.BooleanField(
        default=True,
        help_text="By submitting your proposal, you agree to give permission "
                  "to the conference organizers to record, edit, and release "
                  "audio and/or video of your presentation. If you do not "
                  "agree to this, please uncheck this box."
    )

    accessibility_needs = models.CharField(
        "Do you have specific accessibility needs at the conference?",
        blank=True,
        max_length=1083,
    )
    under_represented_group = models.CharField(
        (
            "Do you identify as a member of an under-represented group "
            "in computing?"
        ),
        choices=YES_NO_OTHER_ANSWERS,
        default="",
        max_length=1,
    )
    under_represented_details = MultiSelectField(
        "I identify as a member of the following underrepresented group(s):",
        blank=True,
        choices=UNDER_REPRESENTED_DETAILED_ANSWERS,
        max_choices=len(UNDER_REPRESENTED_DETAILED_ANSWERS),
    )
    # Text for an prospoal submitter to input additional details about
    # their under represented dimensions.
    under_represented_other = models.CharField(
        "", blank=True, default="", max_length=200
    )
    sponsoring_interest = models.CharField(
        "Would your company be interested in sponsoring the event?",
        choices=YES_NO_SPONSOR_ANSWERS,
        default="",
        max_length=1,
    )
    tracks = TaggableManager(
        blank=True,
        related_name="track_tagged_proposals",
        through=TrackTaggedProposal,
        verbose_name="Tracks",
    )

    editor_keywords = TaggableManager(
        "Editor Keywords",
        blank=True,
        help_text="",
        related_name="editor_tagged_proposals",
        through=EditorTaggedProposal)
    official_keywords = TaggableManager(
        "Keywords",
        blank=True,
        help_text="",
        related_name="official_tagged_proposals",
        through=TaggedProposal)
    user_keywords = TaggableManager(
        "Additional Keywords",
        blank=True,
        help_text="Please add keywords as a comma-separated list.",
        related_name="user_tagged_proposals",
        through=UserTaggedProposal)

    date_created = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name="Created")
    date_last_modified = models.DateTimeField(
        auto_now=True,
        null=True,
        verbose_name="Last Modified")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Update associated presentation if it exists.
        if hasattr(self, "presentation") and self.presentation:
            self.presentation.title = self.title
            self.presentation.description = self.description
            self.presentation.abstract = self.abstract
            self.presentation.speaker = self.speaker
            for speaker in self.additional_speakers.all():
                self.presentation.additional_speakers.add(speaker)
            self.presentation.section = self.section
            self.presentation.save()

        # HTML-ize outline field.
        self.outline_html = parse(self.outline)

        return super(Proposal, self).save(*args, **kwargs)

    def _feedback_count_cache_key(self):
        return "proposal_{}_feedback_count".format(self.pk)

    def _get_cached_vote_count(self, cache_key, vote_score):
        """Helper method to retrieve cached vote counts."""
        cached_vote_count = cache.get(cache_key, False)
        if cached_vote_count is not False:
            return cached_vote_count
        vote_count = ProposalVote.objects.filter(

conf_site/reviews/views/export.py
from django.contrib.auth.models import Group

from conf_site.core.views import CsvView


class ExportReviewersView(CsvView):
    csv_filename = "reviewers.csv"
    header_row = ["ID", "Name", "Email"]

    def get(self, *args, **kwargs):
        reviewers_group = Group.objects.get(name="Reviewers")
        for reviewer in reviewers_group.user_set.all():
            self.csv_writer.writerow(
                [
                    reviewer.id,
                    reviewer.get_full_name(),
                    reviewer.email,
                ]
            )

        return super().get(*args, **kwargs)

conf_site/templates/reviews/_proposal_feedback_tab.html
{% load crispy_forms_tags i18n %}
<div class="tab-pane" id="proposal-feedback">
    {% for feedback in proposal.review_feedback.all %}<hr><p>
      {% if not request.user.is_superuser and config.BLIND_AUTHORS and actor == "speaker" and feedback.author != request.user %}
        <b>Anonymous</b>
      {% elif not request.user.is_superuser and config.BLIND_REVIEWERS and actor == "reviewer" and feedback.author != request.user %}
        <b>Anonymous</b>
      {% else %}
        <b>{{ feedback.author.get_full_name|default:feedback.author.username }}</b>:
      {% endif %}
      {% if request.user.is_superuser or not config.PRIVATE_REVIEWS or actor == "speaker" or feedback.author == proposal.speaker.user or feedback.author == request.user %}
        {{ feedback.comment_html|safe }}
      {% endif %}
    </p>{% endfor %}
      <form method="POST" action="{% url 'review_proposal_feedback' proposal.id %}" class="review-form">
        <legend>Write Feedback:</legend>
        {% csrf_token %}
        <input type="hidden" name="proposal_id" value="{{ proposal.id }}">
        {{ feedback_form|crispy }}
        <div class="form-action">
          <input type="submit" class="btn btn-base-color" name="feedback_submit" value="Submit Feedback" />
        </div>
      </form>
    </p>
  </div>

conf_site/templates/reviews/_proposal_multiedit_buttons.html
<div class="btn-toolbar" role="toolbar" style="margin-bottom: 1rem">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default" name="select_all">
      Select All
    </button>
    <button type="button" class="btn btn-default" name="select_none">
      Select None
    </button>
  </div>
  <div class="btn-group" role="group">
    {% if proposal_category != "Accepted" %}
    <button type="submit" class="btn btn-success btn-status" name="mark_status" value="A">
      <i class="fa fa-thumbs-up" aria-hidden="true"></i> Mark Selected Accepted
    </button>
    {% else %}
    <button type="submit" class="btn btn-success btn-status" name="create_presentations" value="expecto presentation">
        <i class="fa fa-calendar-plus-o" aria-hidden="true"></i> Create Presentations
      </button>
    {% endif %}
    {% if proposal_category != "Rejected" %}
    <button type="submit" class="btn btn-danger btn-status" name="mark_status" value="R">
      <i class="fa fa-thumbs-down" aria-hidden="true"></i> Mark Selected Rejected
    </button>
    {% endif %}
    {% if proposal_category != "Standby" %}
    <button type="submit" class="btn btn-warning btn-status" name="mark_status" value="S">
      <i class="fa fa-pause" aria-hidden="true"></i> Mark Selected Standby
    </button>
    {% endif %}
    {% if proposal_category != "Undecided" %}
    <button type="submit" class="btn btn-default btn-status" name="mark_status" value="U">
        🤷 Mark Selected Undecided
    </button>
    {% endif %}
  </div>
</div>

conf_site/templates/reviews/access_not_permitted.html
{% extends "reviews/base.html" %}

{% block body %}
    <h1>Access Not Permitted</h1>

    <p>
        Sorry, you do not have permission to access this page. If you
        believe this is a bug, please contact us immediately.
    </p>
{% endblock %}

conf_site/templates/reviews/keyword_detail.html
{% extends "reviews/proposal_list.html" %}

{% block page-title %}Proposals: {{ keyword.name }}{% endblock %}

conf_site/templates/reviews/proposal_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}Reviewing - {{ proposal.title }} | {% endblock %}


{% block body %}
<div class="container">
  {% if actor == "reviewer" or  request.user.is_superuser %}
    {% include "reviews/_proposal_mini_navigation.html" %}
  {% endif %}
  <h2>{{ proposal.title }}</h2>

  <p class="bg-info">
    {% if config.BLIND_REVIEWERS and request.user.is_superuser %}
        Your superuser status is ignoring the enabled
        <strong>BLIND_REVIEWERS</strong> setting.
    {% endif %}
    {% if config.PRIVATE_REVIEWS and request.user.is_superuser %}
        Your superuser status is ignoring the enabled
        <strong>PRIVATE_REVIEWS</strong> setting.
    {% endif %}
  </p>

  <div class="pull-right" style="margin-top:-3rem">
    {% if not proposal.cancelled %}
      {% if request.user == proposal.speaker.user %}
        {% if proposal.can_edit %}<a href="{% url "proposal_edit" proposal.pk %}" class="btn btn-default">
          {% translate "Edit this proposal" %}
        </a>{% endif %}
        <a href="{% url "proposal_cancel" proposal.pk %}" class="btn btn-default">
          {% translate "Cancel this proposal" %}
        </a>
      {% elif request.user.is_superuser %}<div class="div-proposal-result-buttons">
        <strong>Status:
        {% if proposal.review_result %}
          {{ proposal.review_result.get_status_display }}
        {% else %}
          Undecided
        {% endif %}</strong><br>
        <a class="btn btn-success" href="{% url 'review_proposal_change_result' proposal.pk 'A' %}"><i class="fa fa-thumbs-up" aria-hidden="true"></i> Approve</a>
        <a class="btn btn-default" href="{% url 'review_proposal_change_result' proposal.pk 'U' %}">🤷 Mark Undecided</a>
        <a class="btn btn-danger" href="{% url 'review_proposal_change_result' proposal.pk 'R' %}"><i class="fa fa-thumbs-down" aria-hidden="true"></i> Reject</a>
        <a class="btn btn-warning" href="{% url 'review_proposal_change_result' proposal.pk 'S' %}"><i class="fa fa-pause" aria-hidden="true"></i> Standby</a>
      </div>{% endif %}
    {% else %}
      {% translate 'Cancelled' }
    {% endif %}
  </div>

  <div class="tabbable">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#proposal-detail" data-toggle="tab">
          {% translate "Proposal Details" %}
        </a>
      </li>
      {% if actor == "reviewer" %}<li>
        <a href="#proposal-reviews" data-toggle="tab">
          {% translate "Reviews" %}
          <span class="badge">{{ proposal.review_votes.count }}</span>
        </a>
      </li>{% endif %}
      <li>
        <a href="#proposal-feedback" data-toggle="tab">
          {% translate "Speaker Feedback" %}
          {% if request.user.is_superuser or not config.PRIVATE_REVIEWS %}
            <span class="badge">{{ proposal.feedback_count }}</span>
          {% endif %}
        </a>
      </li>
    </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="proposal-detail">
      {% include "symposion/proposals/_proposal_fields.html" %}
    </div>
    {# Only show reviews if user is a reviewer. #}
    {% if actor == "reviewer" %}<div class="tab-pane" id="proposal-reviews">
      <h3>Votes</h3>
      {% for review_vote in proposal.review_votes.all %}
      {% if request.user.is_superuser or not config.PRIVATE_REVIEWS or review_vote.voter == request.user %}<hr><p>
        <h4>
          {% if not request.user.is_superuser and config.BLIND_REVIEWERS and review_vote.voter != request.user %}
            Anonymous
          {% else %}
            {{ review_vote.voter.get_full_name|default:review_vote.voter.username }}
          {% endif %}
          ({{ review_vote.get_score_display }})
        </h4>
        {{ review_vote.comment_html|safe }}
      </p>{% endif %}
      {% endfor %}
      <form method="POST" action="{% url 'review_proposal_vote' proposal.id %}" class="review-form">
        <legend>{% if existing_vote %}{% translate 'Update Review' %}{% else %}{% translate 'Submit Review' %}{% endif %}</legend>
        <p>
          Enter your vote and any comment to go along with it.
          You can revise your vote or comment multiple times
          (your previously recorded vote will be replaced).
        </p>
        {% csrf_token %}
        <input type="hidden" name="proposal_id" value="{{ proposal.id }}">
        {{ vote_form|crispy }}
        <div class="form-action">
          <input type="submit" class="btn btn-base-color" name="vote_submit"
              value="{% if existing_vote %}{% translate 'Update Review' %}{% else %}{% translate 'Submit Review' %}{% endif %}">
        </div>
      </form>
    </div>{% endif %}
    {% include "reviews/_proposal_feedback_tab.html" %}
  </div>
</div>
{% endblock %}

conf_site/templates/reviews/proposalkeyword_list.html
{% extends "reviews/proposal_list.html" %}

{% block body %}
<div class="container">
    <h3>Keywords</h3>
    <ul>{% for keyword in keywords %}
        <li>
            <a href="{% url 'review_keyword_detail' keyword.slug %}">
                {{ keyword.name }}
            </a>
        </li>
    {% endfor %}</ul>
</div>
{% endblock %}

conf_site/templates/reviews/review_bulk_accept.html
{% extends "reviews/base.html" %}

{% load bootstrap %}

{% block body %}

    <h1>Bulk Accept</h1>
    <form action="" method="POST" class="uniForm" accept-charset="utf-8">
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" name="submit" value="submit" />
        </div>
    </form>
{% endblock %}

conf_site/templates/reviews/reviewer_list.html
{% extends "reviews/proposal_list.html" %}
{% load crispy_forms_tags i18n review_tags %}
{% load static %}

{% block title %} - Reviewers{% endblock %}

{% block body %}
<div class="container">
  {% include "reviews/_proposal_mini_navigation.html" %}
  <h2>{% block page-title %}Reviewers{% endblock %}</h2>
  {% include "_pagination.html" %}
  <table class="table table-bordered table-hover" id="table-proposals">
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th><i class="fa fa-comment" title="{% trans 'Number of Messages' %}"></i></th>
      <th><span title="Number of +1 Votes">{% trans "+1" %}</span></th>
      <th><span title="Number of +0 Votes"></span>{% trans "+0" %}</span></th>
      <th><span title="Number of -0 Votes"></span>{% trans "-0" %}</span></th>
      <th><span title="Number of -1 Votes"></span>{% trans "-1" %}</span></th>
      <th><span title="Number of Abstentions">{% trans "A" %}</span></th>
      <th><i class="fa fa-question" title="{% trans 'Number of Reviews Still Requested' %}"></i></th>
    </thead>
    <tbody>
      {% for reviewer in user_list %}<tr>
        <td>{{ reviewer.get_full_name }}</td>
        <td><a href="mailto:{{ reviewer.email }}">{{ reviewer.email }}</a></td>
        <td>{{ reviewer.review_feedback.count }}</td>
        <td>{% user_vote_count reviewer 3 %}</td>
        <td>{% user_vote_count reviewer 1 %}</td>
        <td>{% user_vote_count reviewer -1 %}</td>
        <td>{% user_vote_count reviewer -3 %}</td>
        <td>{% user_vote_count reviewer 0 %}</td>
        <td>{% user_vote_count reviewer None %}</td>
      </tr>{% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}