conf_site/api/urls.py
from django.conf.urls import include, re_path
from rest_framework.routers import SimpleRouter

from . import views


# Create a router and register our viewsets with it.
router = SimpleRouter()
router.register(r'speaker', views.SpeakerViewSet)
router.register(r'presentation', views.PresentationViewSet)

urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^$', views.ConferenceDetail.as_view(), name='conference-detail'),
]

conf_site/reviews/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from conf_site.reviews.views import (
    ProposalDetailView,
    ProposalFeedbackPostView,
    ProposalKindListView,
    ProposalReviewRequestedListView,
    ProposalListView,
    ProposalVotePostView,
    ReviewerListView,
)
from conf_site.reviews.views.export import ExportReviewersView
from conf_site.reviews.views.importing import (
    ReviewerCsvImportView,
    ReviewerProposalMatchingCsvImportView,
)
from conf_site.reviews.views.keywords import (
    ReviewKeywordDetailView,
    ReviewKeywordListView,
)
from conf_site.reviews.views.results import (
    ProposalChangeResultPostView,
    ProposalResultListView,
    ProposalMultieditPostView,
)

urlpatterns = [
    path(
        "assigned/",
        ProposalReviewRequestedListView.as_view(),
        name="review_assigned",
    ),
    path(
        "edit/", ProposalMultieditPostView.as_view(), name="review_multiedit"
    ),
    path(
        "keyword/", ReviewKeywordListView.as_view(), name="review_keyword_list"
    ),
    path(
        "keyword/<slug:keyword_slug>/",
        ReviewKeywordDetailView.as_view(),
        name="review_keyword_detail",
    ),
    path(
        "kind/<kind>/",
        ProposalKindListView.as_view(),
        name="review_proposal_kind_list",
    ),
    path(
        "proposal/<int:pk>/",
        ProposalDetailView.as_view(),
        name="review_proposal_detail",
    ),
    path(
        "proposal/<int:pk>/feedback/",
        ProposalFeedbackPostView.as_view(),
        name="review_proposal_feedback",
    ),
    path(
        "proposal/<int:pk>/result/<status>/",
        ProposalChangeResultPostView.as_view(),
        name="review_proposal_change_result",
    ),
    path(
        "proposal/<int:pk>/vote/",
        ProposalVotePostView.as_view(),
        name="review_proposal_vote",
    ),
    path(
        "result/<status>/",
        ProposalResultListView.as_view(),
        name="review_proposal_result_list",
    ),
    path(
        "reviewers/export/",
        staff_member_required(ExportReviewersView.as_view()),
        name="reviewer_export",
    ),
    path(
        "reviewers/import/",
        ReviewerCsvImportView.as_view(),
        name="reviewer_import",
    ),
    path(
        "reviewers/match/",
        ReviewerProposalMatchingCsvImportView.as_view(),
        name="reviewer_matching_import",
    ),
    path("reviewers/", ReviewerListView.as_view(), name="reviewer_list"),
    path("", ProposalListView.as_view(), name="review_proposal_list"),
]

conf_site/urls.py
from django.conf import settings
from django.conf.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path
from django.views.generic.base import TemplateView

try:
    import debug_toolbar
except ImportError:
    pass
import symposion.views

from conf_site.core.views import csrf_failure, TimeZoneChangeView
from conf_site.schedule.views import (
    ExportPresentationSpeakerView,
    PresentationDetailView,
    PresentationRedirectView,
)
from conf_site.speakers.views import (
    ExportAcceptedSpeakerEmailView,
    SpeakerDetailView,
    SpeakerListView,
    SpeakerRedirectView,
)


WIKI_SLUG = r"(([\w-]{2,})(/[\w-]{2,})*)"

if settings.DEBUG:
    urlpatterns = [
        re_path(r"^__debug__/", include(debug_toolbar.urls)),
    ]
else:
    urlpatterns = []
urlpatterns += [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("allauth.urls")),
    re_path(r"^api/", include("conf_site.api.urls")),
    re_path(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
    re_path(
        r"^speaker/export/$",
        staff_member_required(ExportAcceptedSpeakerEmailView.as_view()),
        name="speaker_email_export",
    ),
    re_path(
        r"^speaker/list/$", SpeakerListView.as_view(), name="speaker_list"
    ),
    path(
        "speaker/profile/<int:pk>/",
        SpeakerRedirectView.as_view(),
        name="speaker_profile_redirect",
    ),
    path(
        "speaker/profile/<int:pk>/<slug:slug>/",
        SpeakerDetailView.as_view(),
        name="speaker_profile",
    ),
    re_path(r"^speaker/", include("symposion.speakers.urls")),
    re_path(r"^proposals/", include("conf_site.proposals.urls")),
    re_path(r"^reviews/", include("conf_site.reviews.urls")),
    path(
        "schedule/presentation/<int:pk>/",
        PresentationRedirectView.as_view(),
        name="schedule_presentation_redirect",
    ),
    path(
        "schedule/presentation/<int:pk>/<slug:slug>/",
        PresentationDetailView.as_view(),
        name="schedule_presentation_detail",
    ),
    re_path(
        r"^schedule/presentation/export/$",
        staff_member_required(ExportPresentationSpeakerView.as_view()),
        name="presentation_speaker_export",
    ),
    re_path(r"^schedule/", include("symposion.schedule.urls")),
    re_path(
        r"^time-zone/$", TimeZoneChangeView.as_view(), name="time_zone_change"
    ),
    re_path(r"^403-csrf/", csrf_failure, name="403-csrf"),
    re_path(r"^413/", TemplateView.as_view(template_name="413.html")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

symposion/schedule/urls.py
from django.conf.urls import re_path

from .views import (
    schedule_conference,
    schedule_edit,
    schedule_list,
    schedule_list_csv,
    schedule_detail,
    schedule_slot_edit,
    schedule_json,
)

urlpatterns = [
    re_path(r"^$", schedule_conference, name="schedule_conference"),
    re_path(r"^edit/$", schedule_edit, name="schedule_edit"),
    re_path(r"^list/$", schedule_list, name="schedule_list"),
    re_path(
        r"^presentations.csv$", schedule_list_csv, name="schedule_list_csv"
    ),
    re_path(r"^([\w\-]+)/$", schedule_detail, name="schedule_detail"),
    re_path(r"^([\w\-]+)/edit/$", schedule_edit, name="schedule_edit"),
    re_path(r"^([\w\-]+)/list/$", schedule_list, name="schedule_list"),
    re_path(
        r"^([\w\-]+)/presentations.csv$",
        schedule_list_csv,
        name="schedule_list_csv",
    ),
    re_path(
        r"^([\w\-]+)/edit/slot/(\d+)/",
        schedule_slot_edit,
        name="schedule_slot_edit",
    ),
    re_path(r"^conference.json", schedule_json, name="schedule_json"),
]

conf_site/proposals/models.py
from django.conf import settings
from django.core.cache import cache
from django.db import models

from constance import config
from multiselectfield import MultiSelectField
from symposion.proposals.models import ProposalBase, ProposalSection
from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase

from conf_site.reviews.models import ProposalVote
from symposion.markdown_parser import parse


class ProposalKeyword(TagBase):
    official = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Keyword"
        verbose_name_plural = "Keywords"


class ProposalTrack(TagBase):
    class Meta:
        verbose_name = "Track"
        verbose_name_plural = "Tracks"


class EditorTaggedProposal(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProposalKeyword,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class TaggedProposal(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProposalKeyword,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class UserTaggedProposal(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProposalKeyword,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class TrackTaggedProposal(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProposalTrack,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class Proposal(ProposalBase):

    YES_NO_OTHER_YES = "Y"
    YES_NO_OTHER_NO = "N"
    # https://en.wikipedia.org/wiki/Bartleby,_the_Scrivener
    YES_NO_OTHER_BARTLEBY = "O"

    UNDER_REPRESENTED_ETHNICITY = "R"
    UNDER_REPRESENTED_AGE = "A"
    UNDER_REPRESENTED_GENDER = "G"
    UNDER_REPRESENTED_SEXUAL_ORIENTATION = "S"
    UNDER_REPRESENTED_DISABILITY = "D"
    UNDER_REPRESENTED_SOCIOECON = "C"
    UNDER_REPRESENTED_EDUCATION = "E"
    UNDER_REPRESENTED_OPT_OUT = "O"
    UNDER_REPRESENTED_OTHER = "X"

    KNOWLEDGE_LEVELS = [
        (YES_NO_OTHER_NO, "No previous knowledge expected"),
        (YES_NO_OTHER_YES, "Previous knowledge expected"),
    ]
    YES_NO_BOOL_ANSWERS = (
        (True, "Yes"),
        (False, "No"),
    )
    YES_NO_OTHER_ANSWERS = (
        ("", "----"),
        (YES_NO_OTHER_YES, "Yes"),
        (YES_NO_OTHER_NO, "No"),
        (YES_NO_OTHER_BARTLEBY, "Prefer not to say"),
    )
    YES_NO_SPONSOR_ANSWERS = (
        ("", "----"),
        (YES_NO_OTHER_YES, "Yes, I can make an introduction"),
        (YES_NO_OTHER_NO, "No"),
    )
    UNDER_REPRESENTED_DETAILED_ANSWERS = (
        (UNDER_REPRESENTED_GENDER, "Gender identity"),
        (UNDER_REPRESENTED_SEXUAL_ORIENTATION, "Sexual orientation"),
        (UNDER_REPRESENTED_ETHNICITY, "Race or ethnicity"),
        (UNDER_REPRESENTED_AGE, "Age"),
        (UNDER_REPRESENTED_EDUCATION, "Educational background"),
        (UNDER_REPRESENTED_SOCIOECON, "Socioeconomic status or background"),
        (UNDER_REPRESENTED_DISABILITY, "Disability status"),
        (UNDER_REPRESENTED_OPT_OUT, "I decline to answer"),
        (UNDER_REPRESENTED_OTHER, "Other (please specify)"),
    )

    AFFILIATION_COMPANY = "C"
    AFFILIATION_SCHOOL = "S"
    AFFILIATION_INDEPENDENT = "I"
    AFFILIATIONS = (
        (AFFILIATION_COMPANY, "Company"),
        (AFFILIATION_SCHOOL, "School"),
        (AFFILIATION_INDEPENDENT, "Independent"),
    )

    prior_knowledge = models.CharField(
        choices=KNOWLEDGE_LEVELS,
        max_length=1,
        verbose_name="Prior Knowledge Expected",
    )
    prior_knowledge_details = models.CharField(
        blank=True,
        max_length=200,
        verbose_name=(
            "To attend the presentation, "
            "it would be recommended that "
            "the participant have some knowledge in:"
        ),
    )

    outline = models.TextField(
        "Brief Bullet Point Outline",
        blank=True,
        help_text=(
            "Brief outline. Will be made public "
            "if your proposal is accepted. Edit using "
            "<a href='https://daringfireball.net/projects/markdown/basics' "
            "target='_blank'>Markdown</a>."
        ),
    )
    outline_html = models.TextField(blank=True, editable=False)

    recording_online = models.BooleanField(
        "Is there a recording of this talk/tutorial already online?",
        default=False,
    )
    recording_url = models.URLField(
        blank=True, max_length=2083, verbose_name="If yes, what is the link?"
    )

    slides_url = models.URLField(
        blank=True,
        default="",
        help_text=("Location of slides for this proposal "
                   "(e.g. SlideShare, Google Drive)."),
        max_length=2083,
        verbose_name="Slides")
    code_url = models.URLField(
        blank=True,
        default="",
        help_text="Location of this proposal's code repository (e.g. Github).",
        max_length=2083,
        verbose_name="Repository")

    country = models.CharField(
        max_length=200, verbose_name="What is your country of residence?"
    )

    first_time_at_pydata = models.CharField(
        "Are you a first-time speaker?",
        choices=YES_NO_OTHER_ANSWERS,
        blank=True,
        default="",
        max_length=1)
    travel_at_own_expense = models.BooleanField(
        choices=YES_NO_BOOL_ANSWERS,
        default=True,
        verbose_name=(
            "Are you able to travel to Eindhoven at your own expense?"
        ),
    )
    affiliation = models.CharField(
        max_length=200,
        verbose_name="Affilation (Company, School, Independent)",
    )

    mentorship = models.BooleanField(
        choices=YES_NO_BOOL_ANSWERS,
        default=False,
        verbose_name=(
            "Would you like to be considered "
            "for our speaker mentorship program?"
        ),
    )
    mentoring = models.BooleanField(
        choices=YES_NO_BOOL_ANSWERS,
        default=False,
        verbose_name="Would you be interested in mentoring other speakers?",
    )

    phone_number = models.CharField(
        "Phone number - to be used for last-minute schedule changes",
        blank=True,
        default="",
        max_length=100)
    recording_release = models.BooleanField(
        default=True,
        help_text="By submitting your proposal, you agree to give permission "
                  "to the conference organizers to record, edit, and release "
                  "audio and/or video of your presentation. If you do not "
                  "agree to this, please uncheck this box."
    )

    accessibility_needs = models.CharField(
        "Do you have specific accessibility needs at the conference?",
        blank=True,
        max_length=1083,
    )
    under_represented_group = models.CharField(
        (
            "Do you identify as a member of an under-represented group "
            "in computing?"
        ),
        choices=YES_NO_OTHER_ANSWERS,
        default="",
        max_length=1,
    )
    under_represented_details = MultiSelectField(
        "I identify as a member of the following underrepresented group(s):",
        blank=True,
        choices=UNDER_REPRESENTED_DETAILED_ANSWERS,
        max_choices=len(UNDER_REPRESENTED_DETAILED_ANSWERS),
    )
    # Text for an prospoal submitter to input additional details about
    # their under represented dimensions.
    under_represented_other = models.CharField(
        "", blank=True, default="", max_length=200
    )
    sponsoring_interest = models.CharField(
        "Would your company be interested in sponsoring the event?",
        choices=YES_NO_SPONSOR_ANSWERS,
        default="",
        max_length=1,
    )
    tracks = TaggableManager(
        blank=True,
        related_name="track_tagged_proposals",
        through=TrackTaggedProposal,
        verbose_name="Tracks",
    )

    editor_keywords = TaggableManager(
        "Editor Keywords",
        blank=True,
        help_text="",
        related_name="editor_tagged_proposals",
        through=EditorTaggedProposal)
    official_keywords = TaggableManager(
        "Keywords",
        blank=True,
        help_text="",
        related_name="official_tagged_proposals",
        through=TaggedProposal)
    user_keywords = TaggableManager(
        "Additional Keywords",
        blank=True,
        help_text="Please add keywords as a comma-separated list.",
        related_name="user_tagged_proposals",
        through=UserTaggedProposal)

    date_created = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name="Created")
    date_last_modified = models.DateTimeField(
        auto_now=True,
        null=True,
        verbose_name="Last Modified")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Update associated presentation if it exists.
        if hasattr(self, "presentation") and self.presentation:
            self.presentation.title = self.title
            self.presentation.description = self.description
            self.presentation.abstract = self.abstract
            self.presentation.speaker = self.speaker
            for speaker in self.additional_speakers.all():
                self.presentation.additional_speakers.add(speaker)
            self.presentation.section = self.section
            self.presentation.save()

        # HTML-ize outline field.
        self.outline_html = parse(self.outline)

        return super(Proposal, self).save(*args, **kwargs)

    def _feedback_count_cache_key(self):
        return "proposal_{}_feedback_count".format(self.pk)

    def _get_cached_vote_count(self, cache_key, vote_score):
        """Helper method to retrieve cached vote counts."""
        cached_vote_count = cache.get(cache_key, False)
        if cached_vote_count is not False:
            return cached_vote_count
        vote_count = ProposalVote.objects.filter(

conf_site/reviews/views/export.py
from django.contrib.auth.models import Group

from conf_site.core.views import CsvView


class ExportReviewersView(CsvView):
    csv_filename = "reviewers.csv"
    header_row = ["ID", "Name", "Email"]

    def get(self, *args, **kwargs):
        reviewers_group = Group.objects.get(name="Reviewers")
        for reviewer in reviewers_group.user_set.all():
            self.csv_writer.writerow(
                [
                    reviewer.id,
                    reviewer.get_full_name(),
                    reviewer.email,
                ]
            )

        return super().get(*args, **kwargs)

conf_site/templates/symposion/proposals/_pending_proposal_row.html
{% load i18n %}

<tr>
    <td>
        <a href="{% url "proposal_detail" proposal.pk %}">{{ proposal.title }}</a>
    </td>

    <td>{{ proposal.kind.name }}</td>

    <td>
        {% if proposal.cancelled %}
            <span class="label label-danger">{% translate 'Cancelled' %}</span>
        {% else %}
            <span class="label label-default">{% translate 'Invited' %}</span>
        {% endif %}
    </td>

    <td>
        {% if not proposal.cancelled %}
            <div class="btn-group">
                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                {% translate 'Choose Response' %}
                <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url "proposal_pending_join" proposal.id %}">
			{% translate 'Accept invitation' %}</a></li>
                    <li><a href="{% url 'proposal_pending_decline' proposal.id %}">
            {% translate 'Decline invitation' %}</a></li>
                </ul>
            </div>
        {% endif %}
    </td>
</tr>

conf_site/templates/symposion/proposals/_proposal_fields.html
{% load i18n %}

<dl class="dl-horizontal">
    <dt>{% translate "Category" %}</dt>
    <dd>{{ proposal.kind.name }}</dd>
    {% if not config.BLIND_REVIEWERS or request.user.is_superuser %}
    <dt>{% translate "Submitted by" %}</dt>
    <dd>{{ proposal.speaker.name }}</dd>
    <dt>Affiliation</dt>
    <dd>{{ proposal.get_affiliation_display }}</dd>
    {% endif %}

    {% if config.PROPOSAL_KEYWORDS %}
    {% if request.user != proposal.speaker.user %}
    <dt>Editor Keywords</dt>
    <dd>{% for keyword in proposal.editor_keywords.all %}
        <a href="{% url 'review_keyword_detail' keyword.slug %}">{{ keyword }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}</dd>
    {% endif %}

    <dt>Official Keywords</dt>
    <dd>{% for keyword in proposal.official_keywords.all %}
        <a href="{% url 'review_keyword_detail' keyword.slug %}">{{ keyword }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}</dd>

    <dt>Additional Keywords</dt>
    <dd>{% for keyword in proposal.user_keywords.all %}
        <a href="{% url 'review_keyword_detail' keyword.slug %}">{{ keyword }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}</dd>
    {% endif %}

    <dt>{% translate "Prior Knowledge?" %}</dt>
    <dd>
        {{ proposal.get_prior_knowledge_display }}&nbsp;
        {% if proposal.prior_knowledge == "Y" %}
            <br>{{ proposal.prior_knowledge_details }}
        {% endif %}
    </dd>

    {% if not config.BLIND_REVIEWERS or request.user.is_superuser %}
        {% if proposal.additional_speakers.all %}
            <dt>{% translate "Additional Speakers" %}</dt>
            <dd>
                {% for speaker in proposal.additional_speakers.all %}
                    <li><strong>{{ speaker.name }}</strong></li>
                {% endfor %}
            </dd>
        {% endif %}
    {% endif %}

    <dt>{% translate "Brief Summary" %}</dt>
    <dd>{{ proposal.description }}&nbsp;</dd>

    <dt>{% translate "Outline" %}</dt>
    <dd>{{ proposal.outline_html|safe }}&nbsp;</dd>

    <dt>{% translate "Description" %}</dt>
    <dd>{{ proposal.abstract_html|safe }}&nbsp;</dd>

    {% if proposal.recording_online %}
    <dt>{% translate "Previous Recording" %}</dt>
    <dd><a href="{{ proposal.recording_url }}">{{ proposal.recording_url }}</a></dd>
    {% endif %}

    {% if not config.BLIND_REVIEWERS or request.user.is_superuser %}
    <dt>{% translate "Notes" %}</dt>
    <dd>{{ proposal.additional_notes_html|safe }}&nbsp;</dd>
    {% endif %}

    {% if config.PROPOSAL_URL_FIELDS %}
        {% if proposal.slides_url %}
            <dt>Slides</dt>
            <dd><a href="{{ proposal.slides_url }}">{{ proposal.slides_url }}</a></dd>
        {% endif %}
        {% if proposal.code_url %}
            <dt>Code</dt>
            <dd><a href="{{ proposal.code_url }}">{{ proposal.code_url }}</a></dd>
        {% endif %}
    {% endif %}

    {% if not config.BLIND_REVIEWERS or request.user.is_superuser %}
    <dt>{% translate "Speaker Bio" %}</dt>
    <dd>{{ proposal.speaker.biography_html|safe }}&nbsp;</dd>
    {% endif %}

    <dt>{% translate "Documents" %}</dt>
    <dd>
        {% if proposal.supporting_documents.exists %}
            <table class="table table-striped">
                {% for document in proposal.supporting_documents.all %}
                    <tr>
                        <td><a href="{{ document.download_url }}">{{ document.description }}</a></td>
                        <td>
                        <form style="margin: 0;" method="post" action="{% url "proposal_document_delete" document.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn">delete</button>
                        </form>
                    </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            No supporting documents attached to this proposal.
        {% endif %}
    </dd>
</dl>

conf_site/templates/symposion/proposals/_proposal_row.html
<tr id="proposal-{{ proposal.pk }}">
    <td class="proposal-title">
        <a href="{% url "proposal_detail" proposal.pk %}">{{ proposal.title }}</a>
    </td>

    <td class="proposal-kind">{{ proposal.kind.name }}</td>

    <td class="proposal-result-status">
        {% if proposal.cancelled %}
            <span class="label label-danger">Cancelled</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                <span class="label label-default">Submitted</span>
            {% else %}
                <span class="label label-default">Associated</span>
            {% endif %}
        {% endif %}
    </td>

    <td>
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user and proposal.can_edit %}
                <a href="{% url "proposal_edit" proposal.pk %}" class="btn"><i class="fa fa-pencil"></i> Edit</a>
                <a href="{% url "proposal_speaker_manage" proposal.id %}" class="btn"><i class="fa fa-user"></i> Manage Additional Speakers</a>
            {% endif %}
        {% endif %}
    </td>
</tr>

conf_site/templates/symposion/proposals/document_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Upload Document to '{{ proposal.title }}' | {% endblock %}

{% block body %}
<div class="container">
    <form method="POST" action="" enctype="multipart/form-data" class="form form-horizontal">
        {% csrf_token %}
        <fieldset>
            {{ form|crispy }}
        </fieldset>
        <div class="form-actions">
            <input class="btn btn-base-color" type="submit" value="Upload" />
        </div>
    </form>
</div>
{% endblock %}

conf_site/templates/symposion/proposals/proposal_cancel.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% translate 'Cancel Proposal' %} | {% endblock %}

{% block body %}
<div class="container">
    <h1>Cancel: {{ proposal.title }}</h1>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you want to cancel <b>{{ proposal.title }}</b>?</p>
        <input class="btn btn-danger" type="submit" value="I am sure" />
        <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">{% translate 'No, keep it for now' %}</a>
    </form>
</div>
{% endblock %}

conf_site/templates/symposion/proposals/proposal_submit_kind.html
{% extends "base.html" %}

{% load crispy_forms_tags i18n %}

{% block title %}Submit a Proposal for a {{ kind.name }} | {% endblock %}

{% block body %}
<div class="container">
    <h1>Submit a {{ kind.name }}</h1>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            <legend>An asterisk (<span style="color:red;font-weight:bold">*</span>) indicates a required field.</legend>
            {{ proposal_form|crispy }}
        </fieldset>
        <div class="form-group form-actions">
            <p>
                You will be able to edit your proposal after it has been submitted. The program committee may ask questions, provide feedback, and even suggest changes to your proposal as part of the review processes.
            </p>
            <input class="btn btn-base-color" type="submit" name="finish" value="Save" />
            <!-- <span style="float: right; padding: 4px 6px">or</span> -->
            <input class="btn btn-default" type="submit" name="add-speakers" value="Save and Add Additional Speakers" />
        </div>
    </form>
</div>
{% endblock %}

{% block extra_script %}
<script>
function prior_knowledge_details_display(){
    if( jQuery("#id_prior_knowledge").val() == "Y"){
        jQuery("div#div_id_prior_knowledge_details").show();
    } else {
        jQuery("div#div_id_prior_knowledge_details").hide();
    }
};
function recording_url_display(){
    if( jQuery("#id_recording_online").val() == "True"){
        jQuery("div#div_id_recording_url").show();
    } else {
        jQuery("div#div_id_recording_url").hide();
    }
}
function under_represented_checkbox_display(){
    if( jQuery("#id_under_represented_group").val() == "Y"){
        jQuery("div#div_id_under_represented_details").show();
    } else {
        jQuery("div#div_id_under_represented_details").hide();
    }
};
function under_represented_other_field_display(){
    if( jQuery("#id_under_represented_details_8").is(":checked") ){
        jQuery("div#div_id_under_represented_other").show();
    } else {
        jQuery("div#div_id_under_represented_other").hide();
    }
};
jQuery(document).ready(function(){
    prior_knowledge_details_display();
    recording_url_display();
    under_represented_checkbox_display();
    under_represented_other_field_display();
});
jQuery("#id_prior_knowledge").change(function(){
    prior_knowledge_details_display();
});
jQuery("#id_recording_online").change(function(){
    recording_url_display();
});
jQuery("#id_under_represented_group").change(function(){
    under_represented_checkbox_display();
});
jQuery("#id_under_represented_details_8").change(function(){
    under_represented_other_field_display();
});
</script>
{% endblock %}